# Stage 1: Builder
FROM gitlab-registry.cern.ch/cernvm/build-images/centos_x86_64:9 AS builder

USER root

RUN yum -y install rpm-build fuse
RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

RUN mkdir -p /home/sftnight/buildpackage
RUN mkdir -p /home/sftnight/cvmfs

# Copy tar of the repo
COPY cvmfs-repo.tar.gz /home/sftnight/
RUN mkdir -p /home/sftnight/cvmfs-cache
RUN tar -xzf /home/sftnight/cvmfs-repo.tar.gz -C /home/sftnight/cvmfs-cache
RUN yum -y install rsync
# Now check the diff for ecerything in the cache and copy if there is any diff
RUN cd /home/sftnight; bash cvmfs-cache/test/container/500-concurrent-publishing/scripts/copy_repo.sh

RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage/ cvmfs

# Stage 2: Final
FROM gitlab-registry.cern.ch/cernvm/build-images/centos_x86_64:9

USER root

RUN yum -y install fuse httpd curl

# Copy binaries from the builder stage
COPY --from=builder /home/sftnight/buildpackage/BUILD/cvmfs-2.13.0/cvmfs /usr/local/bin

RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

# Install MinIO client
RUN curl -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc; chmod +x /usr/local/bin/mc

CMD ["/usr/sbin/init"]

